[package]
name = "dcui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
color-eyre = "0.6.3"
ddc-hi = "0.4.1"
derive_setters = "0.1.6"
fakeit = "1.3.0"
itertools = "0.13.0"
lipsum = "0.9.1"
ratatui = "0.29.0"
unicode-width = "0.2.0"

[dev-dependencies]
fakeit = "1.3.0"
