name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/linux.yml

  release:
    needs: [linux]
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
